apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mello-api-v4
  name: mello-api-v4
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: mello-api-v4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mello-api-v4
    spec:
      containers:
      - name: mello-api-v4
        image: jamesmellors/mello-api-v4
        env:
        - name: DB
          value: __DB__
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8002
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: mello-api-v4
  name: mello-api-v4
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8002 #CHANGE
  selector:
    app: mello-api-v4
