apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mello-api-v4
  name: mello-api-v4
  namespace: default
spec:
  # replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: mello-api-v4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mello-api-v4
    spec:
      containers:
      - name: mello-api-v4
        image: jamesmellors/mello-api-v4
        env:
        - name: DB
          value: $(database)
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 80
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: mello-api-v4
  name: mello-api-v4
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8002
    targetPort: 80
  # - port: 8002 #CHANGE
  selector:
    app: mello-api-v4
